# Generated by Django 5.0 on 2025-09-09 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('mobile_No', models.CharField(default='0000000000', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=150)),
                ('mobile_No', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sales', models.FileField(blank=True, null=True, upload_to='sales/')),
                ('purchase', models.FileField(blank=True, null=True, upload_to='purchase/')),
                ('bank', models.FileField(blank=True, null=True, upload_to='bank/')),
                ('other', models.FileField(blank=True, null=True, upload_to='other/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_year', models.IntegerField()),
                ('final_year', models.IntegerField(blank=True, null=True)),
                ('itr', models.FileField(blank=True, null=True, upload_to='itr/')),
                ('computation', models.FileField(blank=True, null=True, upload_to='computation/')),
                ('trading', models.FileField(blank=True, null=True, upload_to='trading/')),
                ('balance', models.FileField(blank=True, null=True, upload_to='balance/')),
                ('audit', models.FileField(blank=True, null=True, upload_to='audit/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners', models.JSONField(blank=True, default=list, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.CharField(max_length=250)),
                ('status', models.CharField(default='Pending', max_length=250)),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Tds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.client')),
            ],
        ),
    ]
