# Generated by Django 5.0 on 2025-09-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdoc',
            name='document',
        ),
        migrations.RemoveField(
            model_name='otherdoc',
            name='year',
        ),
        migrations.AddField(
            model_name='otherdoc',
            name='partners',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
