# Generated by Django 4.2.7 on 2025-08-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.CharField(max_length=250),
        ),
    ]
