# Generated by Django 4.2.7 on 2025-08-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tds_otherdoc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometax',
            name='staff',
        ),
    ]
