# Generated by Django 4.2.7 on 2025-08-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_incometax_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mobile_No',
        ),
        migrations.AddField(
            model_name='client',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
