# Generated by Django 4.2.7 on 2025-08-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_client_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
