# Generated by Django 4.2.7 on 2025-08-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_client_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='mobile_no',
            new_name='mobile_No',
        ),
    ]
