# Generated by Django 4.2.7 on 2025-08-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_mobile_no_client_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mobile_No',
            field=models.BigIntegerField(),
        ),
    ]
